# Generated by Django 4.1 on 2023-04-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0006_create_group_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_dislike',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='course_like',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='course_score',
            field=models.FloatField(default=100, max_length=255),
        ),
    ]
