# Generated by Django 4.1 on 2023-04-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0008_instructor_instructor_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_dislike',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='section_like',
            field=models.CharField(default=1, max_length=255),
        ),
        migrations.AddField(
            model_name='section',
            name='section_score',
            field=models.FloatField(default=100, max_length=255),
        ),
    ]
