# Generated by Django 4.1 on 2023-04-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseinfo', '0013_sectionreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
